version: "3.9"
services:
  postgres:
    container_name: sping-db
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: yoyo
      POSTGRES_PASSWORD: yoyo5555
      POSTGRES_DB: sping-db
    networks:
      - Heepoke

networks:
  Heepoke:
    driver: bridge